// pixmaps.h
#ifndef PIXMAPS_H

static const char *L_close_l_xpm[] = {
	"32 32 2 1",
	"   c None",
	"x  c #000000",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xx                            ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                "};
	
static const char *L_close_r_xpm[] = {
	"32 32 2 1",
	"   c None",
	"x  c #000000",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"                            xx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                "};
	
static const char *L_open_xpm[] = {
	"32 32 2 1",
	"   c None",
	"x  c #000000",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                "};
	
static const char *L_manual_xpm[] = {
	"32 32 2 1",
	"   c None",
	"x  c #000000",
	"                                ",
	"                                ",
	"                                ",
	"           xx     xx            ",
	"           xx     xx            ",
	"    xxxx   xx     xx      xx    ",
	"   xx   x  xx     xx      xx    ",
	"  xx       xx     xx      xx    ",
	"  xx       xx     xx   xxxxxxxx ",
	"  xx       xx     xx   xxxxxxxx ",
	"  xx       xx     xx      xx    ",
	"   xx   x   xx   xx       xx    ",
	"    xxxx     xxxxx        xx    ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"                                ",
	"       xx                       ",
	"       xx        xxxxxx         ",
	"       xx        xx   xxx       ",
	"       xx xxx    xx    xx       ",
	"       xxx  xx   xx    xx       ",
	"       xx    xx  xx    xx       ",
	"       xx    xx  xx   xxx       ",
	"       xx    xx  xxxxxx         ",
	"       xx    xx  xx             ",
	"       xxx  xx   xx             ",
	"       xx xxx    xx             ",
	"                                ",
	"                                ",
	"                                "};

#define PIXMAPS_H
#endif
